---
- name: /var/run/dovecot
  ansible.builtin.file:
    path: /var/run/dovecot
    owner: root
    group: root
    mode: 0755
    state: directory
  notify:
    - Restart dovecot
  tags: postfix_relay

- name: Activate unix_listener
  ansible.builtin.blockinfile:
    dest: /etc/dovecot/conf.d/10-master.conf
    content: |
      service auth {
          unix_listener /var/spool/postfix/private/auth {
            mode = 0600
            user = postfix
            group = postfix
          }
      }
  notify:
    - Restart dovecot
    - Restart postfix
  tags: postfix_relay

- name: Support broken MUA's
  ansible.builtin.lineinfile:
    dest: /etc/dovecot/conf.d/10-master.conf
    regexp: '^auth_mechanisms'
    line: 'auth_mechanisms = plain login'
    state: present
  notify:
    - Restart dovecot
    - Restart postfix
  tags: postfix_relay

- name: Smtpd_sender_login_maps
  ansible.builtin.copy:
    src: login_map
    dest: /etc/postfix/login_map
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload postfix
    - Postmap
  tags: postfix_relay

- name: SASL with submission port
  ansible.builtin.blockinfile:
    dest: /etc/postfix/master.cf
    content: |
      submission inet n - n - - smtpd
        -o smtpd_tls_security_level=encrypt
        -o smtpd_sasl_auth_enable=yes
        -o smtpd_sasl_type=dovecot
        -o smtpd_sasl_path=private/auth
        -o smtpd_sasl_security_options=noanonymous
        -o smtpd_sasl_local_domain=$myhostname
        -o smtpd_client_restrictions=permit_sasl_authenticated,reject
        -o smtpd_sender_login_maps=pcre:/etc/postfix/login_map
        -o smtpd_sender_restrictions=reject_sender_login_mismatch
        -o smtpd_recipient_restrictions=reject_non_fqdn_recipient,reject_unknown_recipient_domain,permit_sasl_authenticated,reject
  notify:
    - Restart dovecot
    - Restart postfix
  tags: postfix_relay

- name: Activate auth-sql.conf
  ansible.builtin.lineinfile:
    dest: /etc/dovecot/conf.d/10-auth.conf
    regexp: '^#!include auth-sql.conf.ext'
    line: '!include auth-sql.conf.ext'
    backrefs: true
  notify:
    - Restart dovecot
  tags: postfix_relay

# See vars/main.yml for dovecot variable definiations
#
- name: Upload authentication database schema
  ansible.builtin.copy:
    src: auth-db.sql
    dest: "{{ dovecot_sql_schema }}"
    owner: root
    group: root
    mode: 0640
  tags: postfix_relay

- name: Create dovecot sqlite3 authentication database
  ansible.builtin.shell: "/usr/bin/sqlite3 {{ dovecot_sql_db }} < {{ dovecot_sql_schema }}"
  register: r
  failed_when: "'table users already exists' not in r.stderr and r.rc != 0"
  changed_when: "'table users already exists' not in r.stderr"
  notify:
    - Restart dovecot
  tags: postfix_relay

- name: Secure authentication database file permissions
  ansible.builtin.file:
    path: "{{ dovecot_sql_db }}"
    owner: root
    group: root
    mode: 0640
  tags: postfix_relay

- name: Use sqlite for authentication database
  ansible.builtin.blockinfile:
    dest: /etc/dovecot/dovecot-sql.conf.ext
    content: |
      driver = sqlite
      connect = {{ dovecot_sql_db }}

      password_query = SELECT userid AS username, domain, password FROM users WHERE userid = '%n' AND domain = '%d'

      user_query = SELECT home, uid, gid FROM users WHERE userid = '%n' AND domain = '%d'

      # For using doveadm -A:
      iterate_query = SELECT userid AS username, domain FROM users
  notify:
    - Restart dovecot
  tags: postfix_relay

- name: Use syslog dovecot logging
  ansible.builtin.lineinfile:
    dest: /etc/dovecot/conf.d/10-logging.conf
    regexp: '^#log_path'
    line: 'log_path = syslog'
    backrefs: true
  notify:
    - Restart dovecot
  tags: postfix_relay

- name: Use mail syslog facility
  ansible.builtin.lineinfile:
    dest: /etc/dovecot/conf.d/10-logging.conf
    regexp: '^#syslog_facility'
    line: 'syslog_facility = mail'
    backrefs: true
  notify:
    - Restart dovecot
  tags: postfix_relay

- name: Log unsuccessful authentication attempts
  ansible.builtin.lineinfile:
    dest: /etc/dovecot/conf.d/10-logging.conf
    regexp: '^#auth_verbose = no'
    line: 'auth_verbose = yes'
    backrefs: true
  notify:
    - Restart dovecot
  tags: postfix_relay
