---
# tasks file for roles/postfix-relay

- name: install postfix-relay packages (apt)
  apt: >
      name="{{ item }} "
      state="latest"
  with_items:
      - postfix
      - postfix-pcre
      - make
  tags: postfix-relay
