---
# tasks file for roles/postfix-relay

- include: debian.yml
  when: ansible_os_family == 'Debian'

- include: ../lib/sudo-safety.yml
  tags: postfix-relay
  
- include: remote-git.yml
  when: postfix_configuration == 'git'
  tags: postfix-relay

- include: local-git.yml
  when: postfix_configuration == 'localhost'
  tags: postfix-relay

- include: template.yml
  when: postfix_configuration == 'template'
  tags: postfix-relay
  
- name: configure aliases database
  template:
	  src:"aliases.j2"
	  dest:"/etc/aliases"
	  owner:"root"
	  group:"root"
	  mode:"0644"
  notify: 
    - newaliases
  tags: postfix-relay
