---
- name: Run preflight assertions
  ansible.builtin.include_tasks: preflight.yml
  tags: always

- name: Gather OS specific variables
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts['distribution_release'] }}.yml"
        - "{{ ansible_facts['distribution'] }}.yml"
        - "{{ ansible_facts['os_family'] }}.yml"
      paths:
        - "vars"
  tags: postfix_relay

- name: Import_tasks debian.yml
  ansible.builtin.import_tasks: debian.yml
  when: ansible_facts['os_family'] == 'Debian'
  tags: postfix_relay

- name: Conf/local-git.yml
  ansible.builtin.import_tasks: conf/local-git.yml
  when: postfix_configuration == 'localhost'
  tags: postfix_relay

- name: Conf/template.yml
  ansible.builtin.import_tasks: conf/template.yml
  when: postfix_configuration == 'template'
  tags: postfix_relay

- name: Configure aliases database
  ansible.builtin.template:
    src: aliases.j2
    dest: /etc/aliases
    owner: root
    group: root
    mode: "0644"
  notify:
    - Newaliases
    - Restart postfix
  tags: postfix_relay

- name: Listen on non-standard port
  ansible.builtin.lineinfile:
    dest: /etc/postfix/master.cf
    regexp: '^{{ postfix_relay_item }}'
    line: '{{ postfix_relay_item }}  inet  n       -       y       -       -       smtpd'
    state: present
  loop: "{{ postfix_ports }}"
  loop_control:
    loop_var: postfix_relay_item
  when:
    - postfix_ports is defined
  notify:
    - Reload postfix
  tags: postfix_relay

- name: Dovecot/main.yml
  ansible.builtin.include_tasks: dovecot/main.yml
  when:
    - postfix_conf.sasl_type is defined
    - postfix_conf.sasl_type == 'dovecot'
  tags: postfix_relay

- name: Import TLS tasks (self-signed)
  ansible.builtin.include_tasks: tls/main.yml
  when:
    - postfix_conf.tls_rsa is defined
    - postfix_conf.tls_rsa == 'self-signed'
  tags: postfix_relay

- name: Import geerlingguy.certbot (lets_encrypt)
  ansible.builtin.include_role:
    name: geerlingguy.certbot
  vars:
    certbot_install_method: package
  when:
    - postfix_conf.tls_rsa is defined
    - postfix_conf.tls_rsa == 'lets_encrypt'
  tags: postfix_relay
