---
- name: gather OS specific variables
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "default.yml"
      paths:
        - "vars"
  tags: postfix_relay

- name: import_tasks debian.yml
  ansible.builtin.import_tasks: debian.yml
  when: ansible_os_family == 'Debian'
  tags: postfix_relay

- name: check for postfix_configuration
  ansible.builtin.fail: msg="postfix_configuration must be defined"
  when: postfix_configuration is undefined
  tags: postfix_relay

- name: include conf/remote-git.yml
  ansible.builtin.include: conf/remote-git.yml
  when: postfix_configuration == 'git'
  tags: postfix_relay

- name: include conf/local-git.yml
  ansible.builtin.include: conf/local-git.yml
  when: postfix_configuration == 'localhost'
  tags: postfix_relay

- name: include conf/template.yml
  ansible.builtin.include: conf/template.yml
  when: postfix_configuration == 'template'
  tags: postfix_relay

- name: configure aliases database
  ansible.builtin.template:
    src: aliases.j2
    dest: /etc/aliases
    owner: root
    group: root
    mode: 0644
  notify:
    - newaliases
    - restart postfix
  tags: postfix_relay

# Find zimbra.real-time.com as the relayhost change it to relay.real-time.com
#
- name: relay host check
  ansible.builtin.lineinfile:
    dest: /etc/postfix/main.cf
    regexp: '^relayhost(\s*)=(\s*)(\[?)zimbra\.real-time\.com(\]?)(.*)$'
    line: 'relayhost = [relay.real-time.com]'
    backrefs: true
  ignore_errors: true
  tags: postfix_relay

- name: listen on non-standard port
  ansible.builtin.lineinfile:
    dest: /etc/postfix/master.cf
    regexp: '^{{ item }}'
    line: '{{ item }}  inet  n       -       y       -       -       smtpd'
    state: present
  with_items:
    - "{{ postfix_ports }}"
  when:
    - postfix_ports is defined
  notify:
    - reload postfix
  tags: postfix_relay

- name: dovecot/main.yml
  ansible.builtin.include: dovecot/main.yml
  when:
    - postfix_sasl_type is defined
    - postfix_sasl_type == 'dovecot'

- name: tls/main.yml
  ansible.builtin.include: tls/main.yml
  when:
    - postfix_tls_rsa is defined
