---
- name: restart postfix
  ansible.builtin.service:
    name: "postfix"
    state: "restarted"
  tags: postfix_relay

- name: reload postfix
  ansible.builtin.service:
    name: "postfix"
    state: "reloaded"
  tags: postfix_relay

- name: newaliases
  ansible.builtin.command: "/usr/bin/newaliases"
  tags: postfix_relay

- name: rebuild db
  ansible.builtin.command: "/usr/bin/make"
  args:
    chdir: "/etc/postfix"
  tags: postfix_relay

- name: restart dovecot
  ansible.builtin.service:
    name: "dovecot"
    state: "restarted"
  tags: postfix_relay

- name: reload dovecot
  ansible.builtin.service:
    name: "dovecot"
    state: "reloaded"
  tags: postfix_relay

- name: update ca-certificates
  ansible.builtin.command: "/usr/sbin/update-ca-certificates"
  register: r
  tags: postfix_relay

- name: postmap
  ansible.builtin.command: "/usr/sbin/postmap {{ post_relay_item }}"
  args:
    chdir: /etc/postfix/
  register: r
  loop:
    - "login_map"
    - "relay_domains"
  loop_control:
    loop_var: post_relay_item
  tags: postfix_relay
