---
- name: gnutls-certs.yml
  ansible.builtin.import_tasks: "{{ role_path }}/../lib/gnutls-certs.yml"
  tags: postfix_relay

- name: deploy TLS certificate and keys
  ansible.builtin.copy:
    src: "{{ postfix_relay_item }}"
    dest: "/etc/ssl/private/{{ postfix_relay_item | basename }}"
    owner: root
    group: ssl-cert
    mode: 0640
  changed_when: false
  loop:
    - "{{ key_pem }}"
    - "{{ cert_pem }}"
  loop_control:
    loop_var: postfix_relay_item
  notify:
    - update ca-certificates
  tags: postfix_relay

- name: combine certificate and key
  ansible.builtin.shell: "/bin/cat {{ key_pem | basename }} {{ cert_pem | basename }} > {{ postfix_myhostname }}.pem"
  args:
    chdir: /etc/ssl/private/
    creates: /etc/ssl/private/{{ postfix_myhostname }}.pem
  changed_when: false
  notify:
    - update ca-certificates
  tags: postfix_relay

- name: fix permissions
  ansible.builtin.file:
    path: /etc/ssl/private/{{ postfix_myhostname }}.pem
    owner: root
    group: ssl-cert
    mode: 0640
  notify:
    - update ca-certificates
  tags: postfix_relay
