---
- name: install postfix main configuration via template
  ansible.builtin.template:
    src: main_cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
  notify:
    - update ca-certificates
    - restart postfix
  tags: postfix_relay

- name: configure mynetworks (list)
  ansible.builtin.lineinfile:
    dest: /etc/postfix/mynetworks
    regexp: '^{{ postfix_relay_item }}(.*)$'
    line: '{{ postfix_relay_item }}'
    create: true
    state: present
    mode: 0644
  when:
    - postfix_mynetworks_conf is not defined
  loop: "{{ postfix_conf.mynetworks }}"
  loop_control:
    loop_var: postfix_relay_item
  notify:
    - reload postfix
  tags: postfix_relay

- name: configure mynetworks (file)
  ansible.builtin.copy:
    src: "{{ postfix_mynetworks }}"
    dest: /etc/postfix/mynetworks
    owner: root
    group: root
    mode: 0644
  when:
    - postfix_mynetworks_conf is defined
    - postfix_mynetworks_conf == 'file'
  notify:
    - postmap
    - reload postfix
  tags: postfix_relay

- name: configure relay_domains (file)
  ansible.builtin.copy:
    src: "{{ postfix_relay_domains }}"
    dest: /etc/postfix/relay_domains
    owner: root
    group: root
    mode: 0644
  when:
    - postfix_relay_domains is defined
    - postfix_relay_domains == 'file'
  notify:
    - postmap
    - reload postfix
  tags: postfix_relay
